octomap_server:
  ros__parameters:
    frame_id: odom
    resolution: 0.15
    sensor_model/max_range: 20.0
    sensor_model/hit: 0.7
    sensor_model/miss: 0.4
    sensor_model/min: 0.12
    sensor_model/max: 0.97
    occupancy_min_z: -0.2
    occupancy_max_z: 6.0
    filter_speckles: true
    publish_free_space: true
    use_sim_time: true
